language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version

  - docker-compose -f docker-compose-build.yaml build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push gusgrins/udagram-api-feed:0.0.1
  - docker push gusgrins/udagram-api-user:0.0.1
  - docker push gusgrins/udagram-frontend:0.0.1
  - docker push gusgrins/reverseproxy:0.0.1