version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: gusgrins/reverseproxy:0.0.2
  backend_user:
    build:
      context: ./udagram-api-user
    image: gusgrins/udagram-api-user:0.0.2
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: gusgrins/udagram-api-feed:0.0.2
  frontend:
    build:
      context: ./udagram-frontend
    image: gusgrins/udagram-frontend:0.0.2