version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:0.0.1
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:0.0.1
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:0.0.1
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:0.0.1